spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/[db]
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      data-locations: classpath:db/init/test-data.sql
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true # Hibernate가 테이블을 다 만든 후 SQL 실행
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 300

  #네이버 smtp 샘플
  mail:
    host: smtp.naver.com
    port: 465
    username: #[네이버 계정(example@naver.com)]
    password: # [네이버 2단계 보안 비밀번호 ]
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com

#swagger - local
springdoc:
  #packages-to-scan: com.kin.jjandolnet.api.domain
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    #groups-order: DESC
    operationsSorter: method
    display-request-duration: true
    tags-sorter: alpha
    persist-authorization: true
  api-docs:
    path: /api-docs

jwt:
  # 최소 32자 이상의 긴 문자열을 권장
  secret:
  expiration-time: # 토큰 유효 시간 (예: 24시간 = 24 * 60 * 60 * 1000ms)